#!/bin/bash

set -eux

# Add flathub
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak install --assumeyes --noninteractive \
        org.kde.ark \
        org.videolan.VLC \
        org.kde.gwenview \
        org.kde.kwrite \
        org.kde.okular \
        org.mozilla.firefox

touch /var/lib/.flatpaks-installed
